# Generated by Django 6.0.6 on 2026-06-18 23:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='Arabic name')),
                ('name_en', models.CharField(max_length=200, verbose_name='English name')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('historical', 'Historical'), ('natural', 'Natural'), ('cultural', 'Cultural'), ('entertainment', 'Entertainment'), ('religious', 'Religious')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tourist_places/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('visiting_hours', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tourist place',
                'verbose_name_plural': 'Tourist places',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TouristRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(help_text='Estimated duration, e.g. "2 hours" or "Full day".', max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('places', models.ManyToManyField(blank=True, related_name='routes', to='tourism.touristplace')),
            ],
            options={
                'verbose_name': 'Tourist route',
                'verbose_name_plural': 'Tourist routes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('tourist_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tourism.touristplace')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'tourist_place'), name='unique_review_per_user_place')],
            },
        ),
    ]
