# Generated by Django 5.2.13 on 2026-06-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_alter_review_id_alter_touristplace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Arabic description'),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='visiting_hours_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Arabic visiting hours'),
        ),
        migrations.AddField(
            model_name='touristroute',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Arabic description'),
        ),
        migrations.AddField(
            model_name='touristroute',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Arabic name'),
        ),
    ]
