# Generated by Django 5.2.13 on 2026-06-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Arabic description'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Arabic location'),
        ),
    ]
