# Generated by Django 6.0.6 on 2026-06-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantFallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_ar', models.TextField(verbose_name='Arabic fallback message')),
                ('message_en', models.TextField(verbose_name='English fallback message')),
            ],
            options={
                'verbose_name': 'Assistant fallback',
                'verbose_name_plural': 'Assistant fallback',
            },
        ),
        migrations.CreateModel(
            name='AssistantReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_ar', models.CharField(max_length=200, verbose_name='Arabic prompt')),
                ('prompt_en', models.CharField(max_length=200, verbose_name='English prompt')),
                ('response_ar', models.TextField(verbose_name='Arabic response')),
                ('response_en', models.TextField(verbose_name='English response')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Extra words to match when the visitor types freely.')),
                ('category', models.CharField(choices=[('general', 'General'), ('places', 'Places'), ('routes', 'Routes'), ('events', 'Events'), ('timing', 'Timing'), ('services', 'Services')], default='general', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_welcome', models.BooleanField(default=False, help_text='Shown once when the chat opens.')),
            ],
            options={
                'verbose_name': 'Assistant reply',
                'verbose_name_plural': 'Assistant replies',
                'ordering': ['order', 'id'],
            },
        ),
    ]
